/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface ExposedVotingProxyInterface extends utils.Interface {
  functions: {
    "DPS()": FunctionFragment;
    "_delegates(address,uint32)": FunctionFragment;
    "_proxyVoters(address,uint32)": FunctionFragment;
    "ballotFactory()": FunctionFragment;
    "grantProxy(address,uint32)": FunctionFragment;
    "hasDelegated(address,uint32)": FunctionFragment;
    "owner()": FunctionFragment;
    "proxyAmount(address,uint32)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setBallotFactory(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DPS"
      | "_delegates"
      | "_proxyVoters"
      | "ballotFactory"
      | "grantProxy"
      | "hasDelegated"
      | "owner"
      | "proxyAmount"
      | "renounceOwnership"
      | "setBallotFactory"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "DPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_delegates",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_proxyVoters",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ballotFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantProxy",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasDelegated",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxyAmount",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBallotFactory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "DPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_delegates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_proxyVoters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ballotFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantProxy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasDelegated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxyAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBallotFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface ExposedVotingProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ExposedVotingProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DPS(overrides?: CallOverrides): Promise<[string]>;

    _delegates(
      to: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    _proxyVoters(
      from: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    ballotFactory(overrides?: CallOverrides): Promise<[string]>;

    grantProxy(
      to: string,
      tagIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasDelegated(
      voter: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proxyAmount(
      voter: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBallotFactory(
      _ballotFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  DPS(overrides?: CallOverrides): Promise<string>;

  _delegates(
    to: string,
    tagIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  _proxyVoters(
    from: string,
    tagIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  ballotFactory(overrides?: CallOverrides): Promise<string>;

  grantProxy(
    to: string,
    tagIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasDelegated(
    voter: string,
    tagIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  proxyAmount(
    voter: string,
    tagIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBallotFactory(
    _ballotFactory: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DPS(overrides?: CallOverrides): Promise<string>;

    _delegates(
      to: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    _proxyVoters(
      from: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    ballotFactory(overrides?: CallOverrides): Promise<string>;

    grantProxy(
      to: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    hasDelegated(
      voter: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    proxyAmount(
      voter: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setBallotFactory(
      _ballotFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    DPS(overrides?: CallOverrides): Promise<BigNumber>;

    _delegates(
      to: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _proxyVoters(
      from: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ballotFactory(overrides?: CallOverrides): Promise<BigNumber>;

    grantProxy(
      to: string,
      tagIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasDelegated(
      voter: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proxyAmount(
      voter: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBallotFactory(
      _ballotFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _delegates(
      to: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _proxyVoters(
      from: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ballotFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    grantProxy(
      to: string,
      tagIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasDelegated(
      voter: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxyAmount(
      voter: string,
      tagIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBallotFactory(
      _ballotFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
