/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISecurity,
  ISecurityInterface,
} from "../../../contracts/interfaces/ISecurity";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "validateTokenTransfer",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
];

export class ISecurity__factory {
  static readonly abi = _abi;
  static createInterface(): ISecurityInterface {
    return new utils.Interface(_abi) as ISecurityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISecurity {
    return new Contract(address, _abi, signerOrProvider) as ISecurity;
  }
}
