/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface BallotInterface extends utils.Interface {
  functions: {
    "DPS()": FunctionFragment;
    "choices(uint256)": FunctionFragment;
    "close()": FunctionFragment;
    "closed()": FunctionFragment;
    "description()": FunctionFragment;
    "factory()": FunctionFragment;
    "getChoices()": FunctionFragment;
    "getVote(address)": FunctionFragment;
    "hasVoted(address)": FunctionFragment;
    "init(address,address,address,string,string,string,string[])": FunctionFragment;
    "isValidChoice(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "proxy()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "resultStorage(bytes32)": FunctionFragment;
    "title()": FunctionFragment;
    "topic()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "vote(string)": FunctionFragment;
    "votingLimit()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DPS"
      | "choices"
      | "close"
      | "closed"
      | "description"
      | "factory"
      | "getChoices"
      | "getVote"
      | "hasVoted"
      | "init"
      | "isValidChoice"
      | "owner"
      | "proxy"
      | "renounceOwnership"
      | "resultStorage"
      | "title"
      | "topic"
      | "transferOwnership"
      | "vote"
      | "votingLimit"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "DPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "choices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "close", values?: undefined): string;
  encodeFunctionData(functionFragment: "closed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getChoices",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getVote", values: [string]): string;
  encodeFunctionData(functionFragment: "hasVoted", values: [string]): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [string, string, string, string, string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidChoice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "proxy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resultStorage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "title", values?: undefined): string;
  encodeFunctionData(functionFragment: "topic", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "vote", values: [string]): string;
  encodeFunctionData(
    functionFragment: "votingLimit",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "DPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "choices", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "close", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getChoices", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidChoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proxy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resultStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "title", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "topic", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingLimit",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Ballot extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BallotInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DPS(overrides?: CallOverrides): Promise<[string]>;

    choices(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    close(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closed(overrides?: CallOverrides): Promise<[boolean]>;

    description(overrides?: CallOverrides): Promise<[string]>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    getChoices(overrides?: CallOverrides): Promise<[string[]]>;

    getVote(voter: string, overrides?: CallOverrides): Promise<[string]>;

    hasVoted(voter: string, overrides?: CallOverrides): Promise<[boolean]>;

    init(
      _DPS: string,
      _proxy: string,
      _factory: string,
      _title: string,
      _description: string,
      _topic: string,
      _choices: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isValidChoice(
      choiceHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proxy(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    resultStorage(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    title(overrides?: CallOverrides): Promise<[string]>;

    topic(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vote(
      choice: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    votingLimit(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  DPS(overrides?: CallOverrides): Promise<string>;

  choices(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  close(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closed(overrides?: CallOverrides): Promise<boolean>;

  description(overrides?: CallOverrides): Promise<string>;

  factory(overrides?: CallOverrides): Promise<string>;

  getChoices(overrides?: CallOverrides): Promise<string[]>;

  getVote(voter: string, overrides?: CallOverrides): Promise<string>;

  hasVoted(voter: string, overrides?: CallOverrides): Promise<boolean>;

  init(
    _DPS: string,
    _proxy: string,
    _factory: string,
    _title: string,
    _description: string,
    _topic: string,
    _choices: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isValidChoice(
    choiceHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  proxy(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  resultStorage(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  title(overrides?: CallOverrides): Promise<string>;

  topic(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vote(
    choice: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  votingLimit(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    DPS(overrides?: CallOverrides): Promise<string>;

    choices(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    close(overrides?: CallOverrides): Promise<void>;

    closed(overrides?: CallOverrides): Promise<boolean>;

    description(overrides?: CallOverrides): Promise<string>;

    factory(overrides?: CallOverrides): Promise<string>;

    getChoices(overrides?: CallOverrides): Promise<string[]>;

    getVote(voter: string, overrides?: CallOverrides): Promise<string>;

    hasVoted(voter: string, overrides?: CallOverrides): Promise<boolean>;

    init(
      _DPS: string,
      _proxy: string,
      _factory: string,
      _title: string,
      _description: string,
      _topic: string,
      _choices: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    isValidChoice(
      choiceHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    proxy(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    resultStorage(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    title(overrides?: CallOverrides): Promise<string>;

    topic(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    vote(choice: string, overrides?: CallOverrides): Promise<void>;

    votingLimit(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    DPS(overrides?: CallOverrides): Promise<BigNumber>;

    choices(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    close(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closed(overrides?: CallOverrides): Promise<BigNumber>;

    description(overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    getChoices(overrides?: CallOverrides): Promise<BigNumber>;

    getVote(voter: string, overrides?: CallOverrides): Promise<BigNumber>;

    hasVoted(voter: string, overrides?: CallOverrides): Promise<BigNumber>;

    init(
      _DPS: string,
      _proxy: string,
      _factory: string,
      _title: string,
      _description: string,
      _topic: string,
      _choices: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isValidChoice(
      choiceHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proxy(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    resultStorage(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    title(overrides?: CallOverrides): Promise<BigNumber>;

    topic(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vote(
      choice: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    votingLimit(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    choices(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    close(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    description(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getChoices(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVote(
      voter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasVoted(
      voter: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    init(
      _DPS: string,
      _proxy: string,
      _factory: string,
      _title: string,
      _description: string,
      _topic: string,
      _choices: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isValidChoice(
      choiceHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    resultStorage(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    title(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    topic(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vote(
      choice: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    votingLimit(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
