/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface BallotFactoryInterface extends utils.Interface {
  functions: {
    "DPS()": FunctionFragment;
    "activeBallotAddresses(uint256)": FunctionFragment;
    "archiveBallot()": FunctionFragment;
    "archivedBallotAddresses(uint256)": FunctionFragment;
    "createBallot(string,string,string,string[])": FunctionFragment;
    "getActiveBallots()": FunctionFragment;
    "getArchivedBallots()": FunctionFragment;
    "implementationAddress()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setImplementationAddress(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DPS"
      | "activeBallotAddresses"
      | "archiveBallot"
      | "archivedBallotAddresses"
      | "createBallot"
      | "getActiveBallots"
      | "getArchivedBallots"
      | "implementationAddress"
      | "owner"
      | "renounceOwnership"
      | "setImplementationAddress"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "DPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "activeBallotAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "archiveBallot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "archivedBallotAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBallot",
    values: [string, string, string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveBallots",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getArchivedBallots",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "implementationAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setImplementationAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "DPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activeBallotAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "archiveBallot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "archivedBallotAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBallot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveBallots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArchivedBallots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementationAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImplementationAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "BallotCreated(address,string,string,string,string[])": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BallotCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface BallotCreatedEventObject {
  ballotAddress: string;
  title: string;
  description: string;
  topic: string;
  choices: string[];
}
export type BallotCreatedEvent = TypedEvent<
  [string, string, string, string, string[]],
  BallotCreatedEventObject
>;

export type BallotCreatedEventFilter = TypedEventFilter<BallotCreatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface BallotFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BallotFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DPS(overrides?: CallOverrides): Promise<[string]>;

    activeBallotAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    archiveBallot(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    archivedBallotAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    createBallot(
      title: string,
      description: string,
      topic: string,
      choices: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getActiveBallots(overrides?: CallOverrides): Promise<[string[]]>;

    getArchivedBallots(overrides?: CallOverrides): Promise<[string[]]>;

    implementationAddress(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setImplementationAddress(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  DPS(overrides?: CallOverrides): Promise<string>;

  activeBallotAddresses(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  archiveBallot(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  archivedBallotAddresses(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  createBallot(
    title: string,
    description: string,
    topic: string,
    choices: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getActiveBallots(overrides?: CallOverrides): Promise<string[]>;

  getArchivedBallots(overrides?: CallOverrides): Promise<string[]>;

  implementationAddress(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setImplementationAddress(
    newAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DPS(overrides?: CallOverrides): Promise<string>;

    activeBallotAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    archiveBallot(overrides?: CallOverrides): Promise<void>;

    archivedBallotAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    createBallot(
      title: string,
      description: string,
      topic: string,
      choices: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    getActiveBallots(overrides?: CallOverrides): Promise<string[]>;

    getArchivedBallots(overrides?: CallOverrides): Promise<string[]>;

    implementationAddress(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setImplementationAddress(
      newAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BallotCreated(address,string,string,string,string[])"(
      ballotAddress?: null,
      title?: null,
      description?: null,
      topic?: null,
      choices?: null
    ): BallotCreatedEventFilter;
    BallotCreated(
      ballotAddress?: null,
      title?: null,
      description?: null,
      topic?: null,
      choices?: null
    ): BallotCreatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    DPS(overrides?: CallOverrides): Promise<BigNumber>;

    activeBallotAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    archiveBallot(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    archivedBallotAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createBallot(
      title: string,
      description: string,
      topic: string,
      choices: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getActiveBallots(overrides?: CallOverrides): Promise<BigNumber>;

    getArchivedBallots(overrides?: CallOverrides): Promise<BigNumber>;

    implementationAddress(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setImplementationAddress(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    activeBallotAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    archiveBallot(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    archivedBallotAddresses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createBallot(
      title: string,
      description: string,
      topic: string,
      choices: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getActiveBallots(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getArchivedBallots(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    implementationAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setImplementationAddress(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
