/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from '../common';

export interface BridgeInterface extends utils.Interface {
  functions: {
    'DPS()': FunctionFragment;
    'SQR()': FunctionFragment;
    'eligibility()': FunctionFragment;
    'owner()': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'setEligibility(address)': FunctionFragment;
    'swapDPStoSQR(uint256)': FunctionFragment;
    'swapSQRtoDPS(uint256)': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'DPS'
      | 'SQR'
      | 'eligibility'
      | 'owner'
      | 'renounceOwnership'
      | 'setEligibility'
      | 'swapDPStoSQR'
      | 'swapSQRtoDPS'
      | 'transferOwnership',
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'DPS', values?: undefined): string;
  encodeFunctionData(functionFragment: 'SQR', values?: undefined): string;
  encodeFunctionData(functionFragment: 'eligibility', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'setEligibility', values: [string]): string;
  encodeFunctionData(functionFragment: 'swapDPStoSQR', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'swapSQRtoDPS', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [string]): string;

  decodeFunctionResult(functionFragment: 'DPS', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'SQR', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'eligibility', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setEligibility', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'swapDPStoSQR', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'swapSQRtoDPS', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;

  events: {
    'OwnershipTransferred(address,address)': EventFragment;
    'SwapDPSToSQR(address,uint256)': EventFragment;
    'SwapSQRToDPS(address,uint256)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'SwapDPSToSQR'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'SwapSQRToDPS'): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<[string, string], OwnershipTransferredEventObject>;

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>;

export interface SwapDPSToSQREventObject {
  investor: string;
  amountSQR: BigNumber;
}
export type SwapDPSToSQREvent = TypedEvent<[string, BigNumber], SwapDPSToSQREventObject>;

export type SwapDPSToSQREventFilter = TypedEventFilter<SwapDPSToSQREvent>;

export interface SwapSQRToDPSEventObject {
  investor: string;
  amountDPS: BigNumber;
}
export type SwapSQRToDPSEvent = TypedEvent<[string, BigNumber], SwapSQRToDPSEventObject>;

export type SwapSQRToDPSEventFilter = TypedEventFilter<SwapSQRToDPSEvent>;

export interface Bridge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BridgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DPS(overrides?: CallOverrides): Promise<[string]>;

    SQR(overrides?: CallOverrides): Promise<[string]>;

    eligibility(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    setEligibility(
      newEligibility: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    swapDPStoSQR(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    swapSQRtoDPS(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;
  };

  DPS(overrides?: CallOverrides): Promise<string>;

  SQR(overrides?: CallOverrides): Promise<string>;

  eligibility(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  setEligibility(
    newEligibility: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  swapDPStoSQR(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  swapSQRtoDPS(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    DPS(overrides?: CallOverrides): Promise<string>;

    SQR(overrides?: CallOverrides): Promise<string>;

    eligibility(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setEligibility(newEligibility: string, overrides?: CallOverrides): Promise<void>;

    swapDPStoSQR(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    swapSQRtoDPS(amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    transferOwnership(newOwner: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    'OwnershipTransferred(address,address)'(
      previousOwner?: string | null,
      newOwner?: string | null,
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(previousOwner?: string | null, newOwner?: string | null): OwnershipTransferredEventFilter;

    'SwapDPSToSQR(address,uint256)'(investor?: string | null, amountSQR?: null): SwapDPSToSQREventFilter;
    SwapDPSToSQR(investor?: string | null, amountSQR?: null): SwapDPSToSQREventFilter;

    'SwapSQRToDPS(address,uint256)'(investor?: string | null, amountDPS?: null): SwapSQRToDPSEventFilter;
    SwapSQRToDPS(investor?: string | null, amountDPS?: null): SwapSQRToDPSEventFilter;
  };

  estimateGas: {
    DPS(overrides?: CallOverrides): Promise<BigNumber>;

    SQR(overrides?: CallOverrides): Promise<BigNumber>;

    eligibility(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    setEligibility(
      newEligibility: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    swapDPStoSQR(amount: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    swapSQRtoDPS(amount: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SQR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eligibility(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    setEligibility(
      newEligibility: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    swapDPStoSQR(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    swapSQRtoDPS(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;
  };
}
