/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as legacy from "./legacy";
export type { legacy };
import type * as vendor from "./vendor";
export type { vendor };
export type { DeepSquare } from "./DeepSquare";
export type { Eligibility } from "./Eligibility";
export type { ReferralProgram } from "./ReferralProgram";
export type { Sale } from "./Sale";
export type { SpenderSecurity } from "./SpenderSecurity";
export type { Vesting } from "./Vesting";
